name: celengan
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  fl_chart: ^1.1.1
  image_picker: ^1.2.1
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # PERBAIKAN 1: Indentasi harus lurus dengan flutter_lints (di dalam dev_dependencies)
  flutter_launcher_icons: ^0.13.1 

# PERBAIKAN 2: Gunakan profile.png karena icon.jpg tidak ada di folder assets
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.jpg" 
  min_sdk_android: 21 

flutter:
  uses-material-design: true
  assets:
    - assets/profile.png
    - assets/surplus.gif
    - assets/stagnan.gif
    - assets/defisit.gif